### ISSUE TITLE
Windows download broken?

### ISSUE THREAD

**Issue by xtough** [cloudfoundry-incubator/multiapps-cli-plugin#27]
when I try to install the cf-mta-plugin from https://tools.hana.ondemand.com/additional/cfcliplugin/cf-cli-mta-plugin-2.0.3-windows-x86_64.exe I get the following error:

cf-cli-mta-plugin-2.0.3-windows-x86_64.exe
panic: runtime error: index out of range

goroutine 1 [running]:
github.wdf.sap.corp/xs2ds/cf-mta-plugin/vendor/github.com/cloudfoundry/cli/plugin.Start(0xbd9b00, 0xc8e180)
        /data/xmake/prod-build10010/w/xs2ds/xs2ds-cf-mta-plugin-OD-linuxx86_64/gen/go-workspace/go-path/src/github.wdf.sap.corp/xs2ds/cf-mta-plugin/vendor/github.com/cloudfoundry/cli/plugin/plugin_shim.go:16 +0x3c4
main.main()
        /data/xmake/prod-build10010/w/xs2ds/xs2ds-cf-mta-plugin-OD-linuxx86_64/gen/go-workspace/go-path/src/github.wdf.sap.corp/xs2ds/cf-mta-plugin/mta_plugin.go:65 +0x4e

**Comment by xtough** [comment]
OK, found the installation routine :-)
Which version is recommended these days? https://tools.hana.ondemand.com/#cloud or GitHub? The latter  is newer (2.0.4). If the former is not maintained anymore, shouldn't it be removed and replaced with by link?

**Comment by enchobelezirev** [comment]
Hello and sorry for the late response,

The latest version of the plugin is always posted on the homepage of the project bu also could be found here https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases.
Currently the latest version is https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/tag/v2.0.7

Also, please use the **cf install-plugin** command in order to install the plugin.

Best regards,
Encho
