### ISSUE TITLE
Partial deployment

### ISSUE THREAD

**Issue by kozubikmichal** [cloudfoundry-incubator/multiapps-cli-plugin#71]
### Description
Currently deploy creates package from all resources and deploys all the content. But let's say I have many UI5 (or any other frontend) applications in one MTA package and I want to push only one of them (because the rest is unchanged). Is this possible/planned behaviour?

Currently I have one UI5 app per MTA but there is another problem with HTML5-Repository where I have to have separate ui deployer for each of this MTA packages, but this is another story.

Having all the applications within one MTA with all other resources would lead to quite a long term operation to push one simple change of the frontend code.

Regards
Michal

**Comment by LukasHeimann** [comment]
A quick workaround would be building just the UIs (invoking `grunt` in the respective directory) and the using the [HTML5 apps repo cf cli plugin](https://github.com/SAP/cf-html5-apps-repo-cli-plugin) to deploy the contents of the `dist` folder.  This would also shortcut building the whole MTAR.

In the long-term, however, having partial deployments would be really great, as having `manifest.yaml`s for everything you might want to push individually is not optimal.

**Comment by enchobelezirev** [comment]
Hello,

There is a feature in the latest release of the plugin which enables the usage of the partial deployment.
The usage is simple: 
- execute deploy or bg-deploy and pass -m <module_name> -m <another_module_name> in order to deploy only certain modules. The same applies for the resources(-r).
- provide --all-modules or --all-resources for deploying all modules/resources
- combine the above two cases

Behavior:
The information about the modules/resources is taken from the deployment descriptor in the current folder. The deployment descriptor is not changed during the deployment! 
An MTAR will be created using the provided information about modules and resources, which will contain the binaries of the modules and resources. The binaries for the modules should be specified via the path module element. The binaries for the resources should specified via the path parameters in the parameters section of the resource.

For more info of the usage: cf help deploy or cf help bg-deploy

Best regards,
Encho

P.S. Before using the feature, update to the latest version of the plugin using the cf install-plugin

**Comment by enchobelezirev** [comment]
The issue is closed because it was not an issue :)
If there is a problem with the deployment, re-open it

**Comment by kozubikmichal** [comment]
Hi Encho, 

thanks for the detailed info, i will try that asap :)

Regards
Michal

**Comment by IObert** [comment]
Hi,

is it possible that this feature is not yet available on the windows version of the plugin?

**Comment by ddonchev** [comment]
@IObert - it's highly unlikely. Can you tell which version of the plugin you're running on win? 
`cf plugins`
